# Generated by Django 5.1 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_username'),
        ('listings', '0012_listing_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_listings',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='listings.listing'),
        ),
    ]
