# Generated by Django 5.1 on 2024-11-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_customuser_age_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, choices=[('18-30', '18-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51-60', '51-60'), ('60+', '60+')], max_length=6, null=True),
        ),
    ]
