# Generated by Django 5.1 on 2024-11-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
