# Generated by Django 5.1 on 2024-12-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_message_sender'),
        ('listings', '0025_alter_listing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='listing_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
        migrations.AddField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing'),
        ),
    ]
