# Generated by Django 5.1 on 2024-12-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_message_content_alter_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
