# Generated by Django 5.1 on 2024-11-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_pets_alter_profile_pref_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
