# Generated by Django 5.1 on 2024-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_in_search',
        ),
        migrations.AddField(
            model_name='profile',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
