services:
  web:
    image: findaroommate:local
    build:
      context: .
      dockerfile: ./Dockerfile  # Path to Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # Use Django's development server
    working_dir: /app 
    volumes:
      - ./findaroommate:/app 
    env_file: ./findaroommate/.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-buster
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_DATABASE}
      
volumes:
  postgres_data:
