services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile  # Path to Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 findaroommate.wsgi:application"
    working_dir: /app
    volumes:
      - ./findaroommate:/app # Mount the whole project directory
      - static_volume:/app/assets
    env_file: ./findaroommate/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-buster
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_DATABASE}
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Your Nginx config file
      - static_volume:/app/assets
    depends_on:
      - web
        
volumes:
  postgres_data:
  static_volume:
