# Generated by Django 5.1 on 2024-10-11 09:35

import django.core.validators
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='build_year',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(listings.models.Listing.current_year), django.core.validators.MinValueValidator(1940)]),
        ),
    ]
