# Generated by Django 5.1 on 2024-10-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_build_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='build_year',
            new_name='year',
        ),
    ]
