# Generated by Django 5.1 on 2024-10-11 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_build_year_listing_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='year',
            new_name='build_year',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(-2)]),
        ),
    ]
