# Generated by Django 5.1 on 2024-10-14 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='build_year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(1940)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(-2)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='own_room',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='roommates',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='smoking',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
