# Generated by Django 5.1 on 2024-10-14 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_bathrooms_alter_listing_build_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='size',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(500)]),
            preserve_default=False,
        ),
    ]
