# Generated by Django 5.1 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pet',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
