# Generated by Django 5.1 on 2024-10-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listinggallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinggallery',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='listings.listing'),
        ),
    ]
