# Generated by Django 5.1 on 2024-10-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listinggallery_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listing_images/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'unique_together': {('listing', 'image')},
            },
        ),
        migrations.DeleteModel(
            name='ListingGallery',
        ),
    ]
