# Generated by Django 5.1 on 2024-10-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listingimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listing_gallery'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='listing_gallery/thumbnails/'),
        ),
    ]
