# Generated by Django 5.1 on 2024-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_alter_listing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
