# Generated by Django 5.1 on 2024-12-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='own_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
